package:
  name: scipoptlib
  version: "3.2.1"

source:
  fn: scipoptsuite-3.2.1.tgz
  url: http://scip.zib.de/download/release/scipoptsuite-3.2.1.tgz
  sha1: 68fcd1eb43efbe33ee062097bc6c04e53ad8a64a
  md5: c8e4d39a447ef651e3d49a3955c24450

build:
  number: 2

requirements:
  build:
    - zlib
    - ipoptlib
  run:
    - zlib
    - ipoptlib

about:
  home: http://scip.zib.de
  license: ZIB academic license
