package:
  name: ipoptlib
  version: "3.12.5"

source:
  fn: Ipopt-3.12.5.tgz
  url: http://www.coin-or.org/download/source/Ipopt/Ipopt-3.12.5.tgz
  md5: be47968fde7761ab609009450247f895
  sha1: 3f63ddfff517235ead17af6cceb426ca858dda37

build:
  number: 1

about:
  home: https://projects.coin-or.org/Ipopt
  license: Eclipse Public License (EPL)
  summary: 'Software package for large-scale nonlinear optimization'
